server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&serverTimezone=UTC
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

app:
  upload:
    directory: uploads
    originals-directory: uploads/originals

  token:
    expiration: 3600